### ISSUE TITLE
Support for Angular 15

### ISSUE THREAD

**Issue by siovene** [amitdahan/ngx-filesize#411]
Hello,
when trying to update my project to Angular 15, I get the following error:

```
./node_modules/ngx-filesize/fesm2020/ngx-filesize.mjs:7:11-19 - Error: export 'default' (imported as 'filesize') was not found in 'filesize' (possible exports: filesize, partial)
```

Could you please look into Angular 15 compatibility?

Thanks!

**Comment by amitdahan** [comment]
Hi @siovene !

Judging from the error message, I suspect you might be using `filesize@^10` instead of the recommended `^9`.

See #397 for the (unfortunate) reasoning.

Let me know if that helped!

(Regardless, while I haven't checked yet, I expect Angular v15 to be supported, but I will probably get to testing & updating our devDeps)

**Comment by siovene** [comment]
Hi @amitdahan,

thank you very much, that was it!
